### ISSUE TITLE
最新版の和訳を統合しませんか？

### ISSUE THREAD

**Issue by SetoAira** [jekyllrb-ja/jekyllrb-ja.github.io#378]
自分が欲しかったため、最新（公式#7708）の和訳を作成しました。（[SetoAira/jekyllrb-ja](https://github.com/SetoAira/jekyllrb-ja)）
こちらに統合していただいた方が、便利だと思うのですがいかがでしょうか？

了解いただけましたら、統合用に手直しを行い、プルリクエストを送信させていただきます。
https://github.com/jekyllrb-ja/jekyllrb-ja.github.io/blob/master/CONTRIBUTING.mdに記載の方法が機能していないようでしたので、この様な形をとらせていただきました。

**Comment by chezou** [comment]
いいと思います。

Organizationのmemberに招待できれば一番いいかなとも思っていますが、memberのinvitation権限僕らは持ってないのでOwnerにお願いするしかないかなと思います。

@gosyujin さん、 SetoAira さんをmember inviteしていただけますか？

cc: @jekyllrb-ja/reviewer

**Comment by SetoAira** [comment]
ひとまず、プルリクエストを送りつけました。
変更点が多いので、最初に基本部分を一括で、その後に和訳サイトとしてみた場合にこの方が良いのではということをポツポツとお送りしています。
後は、ご随意に。

**Comment by gosyujin** [comment]
@chezou メンションありがとうございます。気づきました 💦 
@SetoAira inviteいたしました！

**Comment by SetoAira** [comment]
「えいやでマージしちゃってください！」のお言葉をいただけましたので、マージさせていただきました。
